name: "Upload Android App Release to Amazon Appstore"
description: "GitHub Action for uploading Android APK files to Amazon Appstore. Automatically handles authentication, edit creation, and APK replacement."
author: "AmeyaJain-25"
branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  client_id:
    description: "Amazon AppStore Application Client ID obtained from the Amazon Developer Console"
    required: true
  client_secret:
    description: "Amazon AppStore Application Client Secret obtained from the Amazon Developer Console"
    required: true
  app_id:
    description: "Amazon AppStore Application ID (the unique identifier for your app in the Amazon AppStore)"
    required: true
  apk_release_file:
    description: "Relative path to the Android APK release file (e.g., 'app/build/outputs/apk/release/app-release.apk')"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - run: |
        cd $GITHUB_ACTION_PATH
        echo "Installing dependencies..."
        npm ci
        echo "Running action..."
        node dist/index.js
      shell: bash
