name: "Upload Android App Release to Amazon Appstore"
description: "Github Action for uploading android (.apk) app to Amazon Appstore"
author: "AmeyaJain-25"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  client_id:
    description: "Amazon AppStore Application Client ID"
    required: true
  client_secret:
    description: "Amazon AppStore Application Client Secret"
    required: true
  app_id:
    description: "Amazon AppStore Application ID"
    required: true
  android_apk_release_file:
    description: "Path to the Android APK Release file to upload"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - run: |
        cd $GITHUB_ACTION_PATH
        echo "Installing dependencies..."
        npm install
        echo "Running action..."
        node dist/index.js
      shell: bash
      env:
        INPUT_CLIENT_ID: ${{ inputs.client_id }}
        INPUT_CLIENT_SECRET: ${{ inputs.client_secret }}
        INPUT_APP_ID: ${{ inputs.app_id }}
        INPUT_ANDROID_APK_RELEASE_FILE: ${{ inputs.android_apk_release_file }}
